services:
  mysql:
    image: mysql:8.4
    container_name: boatregistry-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: boat_registry
      MYSQL_USER: boat_user
      MYSQL_PASSWORD: boat_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:

